# base image
FROM python:3.6.5-alpine

RUN apk update && apk add --virtual build-deps gcc python-dev musl-dev && \
  apk add postgresql-dev && apk add netcat-openbsd

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /usr/src/app

CMD ["/usr/src/app/entrypoint.sh"]
